name: CI Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    # 1. On peut définir des variables au niveau du Job
    env:
      APP_ENV: ${{ vars.ENVIRONMENT_NAME }}

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Utilisation des Variables et Secrets dans le Shell
        env:
          # Injection du Secret chiffré dans une variable d'environnement du step
          API_KEY: ${{ secrets.MY_API_KEY }}
        run: |
          echo "Déploiement sur l'environnement : $APP_ENV"
          echo "Tentative de connexion avec la clé API..."
          # GitHub va automatiquement masquer la valeur de $API_KEY par ***
          echo "Ma clé API est : $API_KEY"